Merge pull request #1 from strawberrycheeks/develop
strawberrycheeks/her-majesty pull request #1
Opened 2022-09-15 08:41 UTC by strawberrycheeks

2022-09-27 10:12 UTC, strawberrycheeks commented on src/Contender.cs
> +    public string Name => _name;
Написала саммари к публичным полям и функциям

2022-09-27 16:47 UTC, strawberrycheeks commented on src/Hall.cs
> +                if ((line = reader.ReadLine()) == null) break;
Явно обозначила, что в файле должно быть 100 уникальных имен

2022-10-02 10:57 UTC, strawberrycheeks commented
К каждому имени в списке теперь добавлено прозвище, например: Ричард Львиное Сердце

2022-10-02 14:09 UTC, strawberrycheeks commented
Задача 1 готова

2022-10-04 08:52 UTC, Ningyo requested changes

2022-10-04 08:52 UTC, Ningyo commented on src/Castle.cs
> +    private static int CalculatePrincessPoints(Contender? chosenPrince)
странно, что кто-то извне принцессы определяет её счастье

2022-10-04 08:52 UTC, Ningyo commented on src/Castle.cs
> +            return 10;
magic numbers

2022-10-04 08:52 UTC, Ningyo commented on src/Contender.cs
> +    /// Score of the contender. If score > 50, it equals to the 'happiness'
If score > 50, - не обязательно писать. это уже к алгоритму относится, а не к сущности претендента

2022-10-04 08:52 UTC, Ningyo commented on src/LadyInWaiting.cs
> +        return contender.Score == _bestContenderScore;
1. == немножко опасное место, здесь присутствует неявная зависимость от порядка вызова методов. лучше >= написать, мне кажется
2. нет проверки, что претендент посещён

2022-10-04 08:52 UTC, Ningyo commented on src/strategy/IStrategy.cs
> +    public Contender? ChooseBestContender(List<Contender> contenders, LadyInWaiting ladyInWaiting);
саммари

2022-10-04 08:52 UTC, Ningyo commented on src/strategy/OptimalStrategy.cs
> +    public Contender? ChooseBestContender(List<Contender> contenders, LadyInWaiting ladyInWaiting)
когда будете настраивать DI контейнер, лучше, чтобы подруга была полем в стратегии, а не параметром функции. т.к. подруга всё равно одна на всё приложение

2022-10-04 09:02 UTC, strawberrycheeks commented on src/Castle.cs
> +    private static int CalculatePrincessPoints(Contender? chosenPrince)
Переместила в класс Princess, теперь это её публичный метод

2022-10-04 09:03 UTC, strawberrycheeks commented on src/Contender.cs
> +    /// Score of the contender. If score > 50, it equals to the 'happiness'
убрала

2022-10-04 09:31 UTC, strawberrycheeks commented on src/strategy/OptimalStrategy.cs
> +    public Contender? ChooseBestContender(List<Contender> contenders, LadyInWaiting ladyInWaiting)
Подруга теперь поле в стратегии

2022-10-04 09:39 UTC, strawberrycheeks commented on src/LadyInWaiting.cs
> +        return contender.Score == _bestContenderScore;
Добавила проверку, что претендент посещён
над пунктом 1 ещё думаю

2022-10-04 10:13 UTC, strawberrycheeks commented on src/LadyInWaiting.cs
> +        return contender.Score == _bestContenderScore;
Поставила >=, переименовала: 
_bestContenderScore ->_bestVisitedScore,
IsBetterThanPrevious -> IsBetterThanVisited, 
contenderList -> VisitedContenderList

Проверку, что претендент посещён, вынесла в отдельный метод isVisited

2022-10-04 10:16 UTC, strawberrycheeks commented on src/strategy/IStrategy.cs
> +    public Contender? ChooseBestContender(List<Contender> contenders, LadyInWaiting ladyInWaiting);
Добавила саммари

2022-10-04 10:28 UTC, strawberrycheeks commented on src/Castle.cs
> +            return 10;
добавила приватные константы для принцессы

2022-10-09 02:57 UTC, Ningyo commented on src/LadyInWaiting.cs
> +        return contender.Score == _bestContenderScore;
1. >= вижу, хорошо)
2. проверку посещённости в IsBetterThanVisited не вижу. вижу, что она отдельно в стратегии написана, но это тоже опасное место - ничто не запрещает нам вызвать IsBetterThanVisited с любым вообще претендентом.

2022-10-09 02:59 UTC, Ningyo commented on src/Castle.cs
> +            return 10;
в замке остались 0 и 10 в свитче)

2022-10-09 03:05 UTC, Ningyo requested changes

2022-10-09 03:05 UTC, Ningyo commented on src/Princess.cs
> +    public static int CalculateHappinessPoints(Contender? prince)
всё ещё не очень хорошо, что принцесса по сути в любой момент времени может доступиться к Score претендента - зачем тогда ей вообще какую-то сложную стратегию иметь. смотрите, считать счастье - похоже на ответственность принцессы, тут всё хорошо. иметь доступ к Score претендента - плохо, это сводит на нуль все усилия по написанию алгоритма. но никто не запрещает принцессе просто уметь расчитывать счастье от пришедшего в параметре Score, например. или уметь спрашивать у холла один единственный раз за жизнь, сколько стоит претендент по имени (но тут сложнее, нужно проверять, что принцесса не будет этим злоупотреблять)

2022-10-09 03:55 UTC, Ningyo commented on src/LadyInWaiting.cs
> +        return contender.Score == _bestContenderScore;
теперь вижу, что исправили

2022-10-09 04:10 UTC, Ningyo requested changes

2022-10-09 04:10 UTC, Ningyo commented on src/strategy/OptimalStrategy.cs
> +                && _ladyInWaiting.IsBetterThanVisited(contender)) // Important: contender must be already visited!
комментарии в одну строку с кодом сложно читать) лучше такое только в крайнем случае использовать и только в коротких строках

2022-10-09 04:17 UTC, Ningyo commented on src/Princess.cs
> +    public static int CalculateHappinessPoints(Contender? prince)
не сказала бы, что что-то сильно изменилось от вынесения списка претендентов в стратегию) стратегия - это способ организации решения, но по сути она делает работу принцессы - выбирает претендента, и точно так же имеет доступ к полям претендента. но ладно, оставим это так пока.

2022-10-09 04:20 UTC, merged