Merge pull request #2 from strawberrycheeks/develop
strawberrycheeks/her-majesty pull request #2
Opened 2022-10-25 05:11 UTC by strawberrycheeks

2022-10-25 08:47 UTC, Ningyo requested changes

2022-10-25 08:47 UTC, Ningyo commented on src/appsettings.json
> +﻿
вы хотели добавить названия файлов сюда

2022-10-25 12:09 UTC, strawberrycheeks commented
Я подумала о том, что хотела бы писать список всех посещённых претендентов в лог, а не в файл с результатом. Но не знаю, стоит ли так делать? Имеет ли это смысл? 

С одной стороны, лог -- это список событий, произошедших в программе, значит, посещение претендентов вполне может там быть; это ведь считается за событие в программе? К тому же оно помогает проверять, что алгоритм работает корректно

С другой стороны, возможно, в лог обычно пишут информацию другого рода? Ну там, обработка запросов сервером, например. Так что не уверена, будет ли список претендентов там выглядеть уместно

2022-10-26 14:01 UTC, Ningyo commented
отвечая на ваш вопрос про лог: в принципе, можете в лог, а не в файл. это не очень принципиальное требование к задаче) но будет здорово, если вы ещё и с логированием разберётесь. вы какое логирование хотели использовать?

2022-10-26 14:34 UTC, strawberrycheeks commented
Там есть ILogger<Princess>, я думала о том, чтобы его использовать. Тогда можно было бы логировать как LogDebug, но пока ещё не разобралась, как указать уровень логирования (он по умолчанию вроде как выше, чем Debug, и из-за этого сообщения не выводятся)

2022-11-15 17:46 UTC, strawberrycheeks commented
appsettings.json подключить все-таки удалось! Но следом столкнулась с другой проблемой: заметила, что в консоль выводятся не все сообщения логгера, которые должны там быть. Каждый раз, когда принцесса просматривала всех 100 претендентов и никого не выбирала, печатал разное количество просмотренных кандидатов. Выглядит, будто логгер при завершении работы хоста не пишет то, что осталось в буфере, а никакого метода типа Flush у ILogger<> не нашлось.

В одном из ответов на StackOverflow нашла, что MS официально рекомендует использовать 3rd-party логгеры для логирования в файл, так что использовала nreco/logging (https://github.com/nreco/logging)

Итого:
• лог пишется только, когда EnvironmentName == Development, т.е. обычно при запуске не пишется;
• лог пишется в файл с названием "logs/app-{0:yyyy}-{0:MM}-{0:dd}-{0:HH}-{0:mm}-{0:ss}.log";
• выглядит это "чудо" вот так:
![image](https://user-images.githubusercontent.com/70949838/201989347-6856e061-74d7-4eb1-a9a0-6f96856ba11f.png)

Не хочу показаться занудой, но это было что-то вроде дела принципа, а то у меня диплом про написание логгера... Так что просто сдаться я не могла

2022-11-16 06:15 UTC, strawberrycheeks commented on src/appsettings.json
> +﻿
Заменила класс Constants на класс AppSettings, добавила загрузку из appsettings.json

2022-11-16 06:55 UTC, strawberrycheeks commented
Вот на этом коммите обновились все файлы, потому что добавила проект для тестов и весь предыдущий проект нужно было перенести в отдельную папку (до этого он лежал в одной папке с решением)

2022-11-18 05:48 UTC, strawberrycheeks commented
Я подумала ещё раз и решила коммиты с тестами для 3 задачи вынести в отдельный мердж-реквест... а тут всё отменила...

2022-11-20 08:01 UTC, Ningyo commented
>>Не хочу показаться занудой, но это было что-то вроде дела принципа, а то у меня диплом про написание логгера... Так что просто сдаться я не могла
тогда хорошо, что удалось потрогать стандартное логирование) если интересно, можете посмотреть стек ELK (Elasticsearch, Logstash и Kibana) - используем в работе, классная штука. но прикручивать сюда его смысла не много будет, лучше успеть следующих задач порешать, чем с ним возиться))

2022-11-20 08:01 UTC, merged