Merge pull request #3 from strawberrycheeks/develop
strawberrycheeks/her-majesty pull request #4
Opened 2022-11-20 09:15 UTC by strawberrycheeks

2022-11-20 09:33 UTC, strawberrycheeks commented
А как лучше поступить с тестами для холла, если имена претендентов считываются из файла? В юнит-тестах можно использовать файлы?

2022-11-23 12:49 UTC, Ningyo commented
> А как лучше поступить с тестами для холла, если имена претендентов считываются из файла? В юнит-тестах можно использовать файлы?

если у вас из файла читает генератор - оставьте чтение для тестов генератора. холлу скорее всего всё равно, откуда там считались претенденты, так что можно их просто замокать - или реализовать моковый генератор (тогда холл должен использовать интерфейс генератора, а не конкретный генератор), или какую-нибудь библиотеку для моков использовать, и говорить каждый раз генератору через неё "а вот теперь ты такой список возвращаешь". знаю Moq - может, ещё что-нибудь найдёте)

2022-12-13 08:40 UTC, Ningyo requested changes

2022-12-13 08:40 UTC, Ningyo commented on HerMajestyTests/FriendTests.cs
> +        act.Should().Throw<UnvisitedContenderComparedException>();
можно сообщение проверить, если оно у вас есть

2022-12-13 08:40 UTC, Ningyo commented on HerMajestyTests/FriendTests.cs
> +        friend.AddVisitedContender(averageContender);
AddVisitedContender тоже можно потестить. что будет напр, если передать null

2022-12-13 08:40 UTC, Ningyo commented on HerMajestyTests/PrincessTests.cs
> +    private static Princess SetupPrincessForTest(List<Contender> contenders)
когда сделаете генератор претендентов, этот метод можно переделать в честный SetUp и по месту в каждом тесте говорить генератору, что он будет возвращать

2022-12-20 04:28 UTC, strawberrycheeks commented on HerMajestyTests/FriendTests.cs
> +        act.Should().Throw<UnvisitedContenderComparedException>();
Добавила проверку сообщения

2022-12-20 04:41 UTC, strawberrycheeks commented on HerMajestyTests/FriendTests.cs
> +        friend.AddVisitedContender(averageContender);
Для этого случая дописала проверку в методе AddVisitedContender, хотя и теперь Райдер на меня ругается:
![image](https://user-images.githubusercontent.com/70949838/208584469-5f8c9582-374a-4b77-9dc4-94d1ed35cb53.png)

Методу AddVisitedContender добавила возвращаемое значение bool, дописала два теста на случаи false и true

2022-12-20 05:11 UTC, strawberrycheeks commented on HerMajestyTests/PrincessTests.cs
> +    private static Princess SetupPrincessForTest(List<Contender> contenders)
Сделала генератор и метод SetUp в тестах

2022-12-20 07:46 UTC, Ningyo requested changes

2022-12-20 07:46 UTC, Ningyo commented on HerMajestyTests/res/100-unique-names.txt
> +Aaron the Mountain of Strength
лучше было бы проверять настоящий файл, а не тестовый. иначе вы не можете быть уверены, что у вас генератор при настоящем запуске будет использовать корректные данные

2022-12-20 07:57 UTC, strawberrycheeks commented on HerMajestyTests/res/100-unique-names.txt
> +Aaron the Mountain of Strength
Заменила на проверку настоящего файла, тестовый удалила

2022-12-20 08:29 UTC, strawberrycheeks commented
Добавить appsettings для проекта с тестами
либо
Использовать моки

2022-12-21 11:33 UTC, strawberrycheeks commented on HerMajestyTests/res/100-unique-names.txt
> +Aaron the Mountain of Strength
Добавила appsettings для проекта с тестами, путь до файла считывается из AppSettings

2022-12-21 14:39 UTC, merged