Merge pull request #5 from strawberrycheeks/develop
strawberrycheeks/her-majesty pull request #5
Opened 2022-12-26 04:01 UTC by strawberrycheeks

2022-12-26 09:54 UTC, strawberrycheeks commented
И на тестах она погибла... Что это за [страшилки](https://learn.microsoft.com/ru-ru/ef/ef6/fundamentals/testing/mocking?redirectedfrom=MSDN#:~:text=%D0%B2%20%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8%20dbSet.-,%D0%A7%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%2C%20%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%20%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C%20%D0%B2%20%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8%20DbAsyncQueryProvider,-%D0%B4%D0%BB%D1%8F%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE) такие?...

2022-12-26 11:01 UTC, strawberrycheeks commented
Кажется, 4 лабу сделала!
Тест на считывание попытки находится CastleTests, если что

2022-12-26 13:52 UTC, Ningyo requested changes

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/Program.cs
> +            Console.WriteLine(ex is FormatException or OverflowException
с FormatException вроде ещё понятно, а почему при OverflowException должно быть Expected argument: <attempt-id> should be an integer?

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Migrations/20221226015218_CreateAttempts.cs
> +                    Name = table.Column<string>(type: "text", nullable: true),
обнуляемое имя? вы уверены?)

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Model/Castle.cs
> +        var attempts = _attemptRepository
await

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Model/Castle.cs
> +            _hall.FillContendersList(int.Parse(at.AttemptNumber));
почему бы просто не сделать AttemptNumber числовым, если вы тут всё равно предполагаете число? это потенциальное место для ошибки, раз в AttemptNumber можно записать любой текст

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Model/Hall.cs
> +        if (attemptEntity.Result == null)
await. если есть асинхронный метод - надо бы и вызывать его асинхронно. иначе вы блокируете поток и убиваете всю фишку асинхронности

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Repository/AttemptRepository.cs
> +    private readonly PostgresDbContext _dbc;
можно нормальное название выбрать) не очень понятно с первого взгляда, что имели в виду

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Repository/IAttemptRepository.cs
> +    // void AddBlog(AttemptEntity blog);
не нужно?

2022-12-26 13:52 UTC, Ningyo commented on HerMajesty/src/Util/AppSettings.cs
> +    public static string DbConnection { get; private set; } = "Host=localhost;Port=5432;Database=hermajesty;Username=admin;Password=1234";
у вас же есть в конфигурации уже. зачем здесь дублировать полностью? если вы не прочитали конфигурацию по каким-то причинам, или забыли её подключить - у приложения в принципе проблемы какие-то, нет смысла их замалчивать со значениями по умолчанию

2022-12-26 13:52 UTC, Ningyo commented on HerMajestyDatabase/.dockerignore
> +README.md
ридми-то зачем в игнор?) ридми обычно полезная штука

2022-12-26 13:52 UTC, Ningyo commented on HerMajestyTests/CastleTests.cs
> +public class CastleTests
у вас эти тесты разве отличаются чем-то от тестов принцессы, которые раньше были? одно и то же нет смысла повторять. но вроде у вас в замке есть расчёт среднего счастья, которое можно проверить, как раз

2022-12-26 14:01 UTC, strawberrycheeks commented on HerMajesty/Program.cs
> +            Console.WriteLine(ex is FormatException or OverflowException
Оба эти исключения предусмотрены для метода int.Parse(), который используется, чтобы из аргументов номер попытки получить

2022-12-26 14:02 UTC, strawberrycheeks commented on HerMajestyDatabase/.dockerignore
> +README.md
это .dockerignore, я его не вручную составляла... Убрала

2022-12-26 14:03 UTC, strawberrycheeks commented on HerMajesty/src/Repository/IAttemptRepository.cs
> +    // void AddBlog(AttemptEntity blog);
Ой, да, это из примера было! Убрала

2022-12-26 14:08 UTC, Ningyo commented on HerMajestyDatabase/.dockerignore
> +README.md
а. не заметила что-то) прочитала как гитигнор. нене, тогда оставьте, если оно само сгенерилось, пусть будет

2022-12-26 14:09 UTC, Ningyo commented on HerMajesty/Program.cs
> +            Console.WriteLine(ex is FormatException or OverflowException
оке. хотя не очень очевидно. может, вам лучше какое-нибудь TryParse использовать?

2022-12-26 14:21 UTC, strawberrycheeks commented on HerMajesty/src/Repository/AttemptRepository.cs
> +    private readonly PostgresDbContext _dbc;
Заменила dbc на context

2022-12-26 16:55 UTC, strawberrycheeks commented on HerMajesty/src/Util/AppSettings.cs
> +    public static string DbConnection { get; private set; } = "Host=localhost;Port=5432;Database=hermajesty;Username=admin;Password=1234";
Убрала значение по умолчанию

2022-12-26 17:34 UTC, strawberrycheeks commented on HerMajesty/src/Migrations/20221226015218_CreateAttempts.cs
> +                    Name = table.Column<string>(type: "text", nullable: true),
Изменила, в entity стоял тип string? Миграции сгенерировала заново

2022-12-26 17:44 UTC, strawberrycheeks commented on HerMajesty/src/Model/Castle.cs
> +            _hall.FillContendersList(int.Parse(at.AttemptNumber));
Изменила тип AttemptNumber на целое число

2022-12-26 17:49 UTC, strawberrycheeks commented on HerMajesty/src/Model/Castle.cs
> +        var attempts = _attemptRepository
Добавила await

2022-12-26 17:49 UTC, strawberrycheeks commented on HerMajesty/src/Model/Hall.cs
> +        if (attemptEntity.Result == null)
Добавила await

2022-12-26 18:06 UTC, strawberrycheeks commented on HerMajesty/Program.cs
> +            Console.WriteLine(ex is FormatException or OverflowException
Заменила на использование TryParse

2022-12-27 08:24 UTC, Ningyo commented on HerMajestyTests/CastleTests.cs
> +public class CastleTests
замок можно вынести в отдельный сервис и отделить его от запуска. нужно заранее думать, как тестировать)

2022-12-27 08:24 UTC, merged